### PR TITLE
make underscore `_` and reserved symbols like `=>` rendered as symbols

### PR DESCRIPTION
**Pull request by enzief**

### CODE REVIEW

**Comment by hvesalai** [comment]
Could you perhaps try to somehow justify this PR. The lines commented out are obviously meant to be there (they don't look like a bug), so this PR doesn't _fix_ anything, it changes things.

Now the question is, why would this change be good? `_` and `=>` are reserved keywords unlike, say `->`, which is a normal extension method.

**Comment by enzief** [comment]
Hello, thanks for looking at this.
I changed the title as suggested, indeed it doesn't make sense  as a fix.

So if `=>` is seen as keyword I'd say it hard to read from the line below where consecutive `case`, `=>`, and `val` are highlighted in the same color.
```scala
case x => val a = 1
```
For another case, `=>` is a type alias for function type, not a keyword. Seeing `A => B` with keyword `=>` is really confusing to me.

For `_`, it's highlighted as part of the identifier `sdf_dfsdf`, which doesn't look right.

**Comment by hvesalai** [comment]
`_` is not highlighted in `sdf_dfsf` at least for me. If you see it highlighted, then that is a bug that must be fixed by not tagging it as a keyword in that context  (as it works for me).

image

As for `=>` (and `_` alone), I think they are reserved "words" and as such I want them highlighted. That means I cannot accept this change as such. _However, I could accept a PR that made this configurable so that each developer can decide for them selves. I'd still keep the default as it is.

**Comment by enzief** [comment]
The thing is my elisp level is merely at adding `;` to comment the line. Now I can only hope for someone else capable of making the change.
Thanks for reviewing.

**Pull request closed without merging**
